"""add_winner_id

Revision ID: f0fcfc0e433e
Revises: 141643ca39b0
Create Date: 2023-04-06 03:07:32.285814

"""
from alembic import op
from alembic import context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0fcfc0e433e'
down_revision = '141643ca39b0'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if not context.get_x_argument(as_dictionary=True).get('disable-data', None):
        data_upgrades()
    post_data_schema_upgrades()


def downgrade():
    before_data_schema_downgrades()
    if not context.get_x_argument(as_dictionary=True).get('disable-data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('winner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'user', ['winner_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'winner_id')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass


def post_data_schema_upgrades():
    pass


def before_data_schema_downgrades():
    pass
