"""add_max_games_column

Revision ID: 089ac149e40b
Revises: 589062bc221f
Create Date: 2023-03-22 23:54:18.692987

"""
from alembic import op
from alembic import context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089ac149e40b'
down_revision = '589062bc221f'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if not context.get_x_argument(as_dictionary=True).get('disable-data', None):
        data_upgrades()
    post_data_schema_upgrades()


def downgrade():
    before_data_schema_downgrades()
    if not context.get_x_argument(as_dictionary=True).get('disable-data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lobby', sa.Column('max_games', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lobby', 'max_games')
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass


def post_data_schema_upgrades():
    pass


def before_data_schema_downgrades():
    pass
