"""make_game_player_id_nullable

Revision ID: 141643ca39b0
Revises: 089ac149e40b
Create Date: 2023-04-05 00:25:10.042785

"""
from alembic import op
from alembic import context
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141643ca39b0'
down_revision = '089ac149e40b'
branch_labels = None
depends_on = None


def upgrade():
    schema_upgrades()
    if not context.get_x_argument(as_dictionary=True).get('disable-data', None):
        data_upgrades()
    post_data_schema_upgrades()


def downgrade():
    before_data_schema_downgrades()
    if not context.get_x_argument(as_dictionary=True).get('disable-data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass


def post_data_schema_upgrades():
    pass


def before_data_schema_downgrades():
    pass
