USER_ALREADY_IN_LOBBY = "User already in lobby"
WRONG_PHONE_OR_PASSWORD = "Wrong phone or password"
ALREADY_CONFIRMED = "Already confirmed"
NOT_CONFIRMED = "Not confirmed"
DOES_NOT_EXISTS = "Does not exists"
PHONE_USER_DOES_NOT_EXIST = "Phone user does not exist"